DECLARE @vROUTINE_SCHEMA NVARCHAR(256)
DECLARE @vROUTINE_NAME SYSNAME
DECLARE @vROUTINE_TYPE NVARCHAR(40)
DECLARE @vROUTINE_DEFINITION NVARCHAR(MAX)

DECLARE @vSFVT_Query NVARCHAR(MAX) = ''

DECLARE create_table_script_cur CURSOR FOR     
SELECT TOP 10 ROUTINE_SCHEMA,ROUTINE_NAME,ROUTINE_TYPE,ROUTINE_DEFINITION FROM INFORMATION_SCHEMA.ROUTINES ORDER BY ROUTINE_TYPE
  
OPEN create_table_script_cur    
  
FETCH NEXT FROM create_table_script_cur INTO @vROUTINE_SCHEMA,@vROUTINE_NAME,@vROUTINE_TYPE,@vROUTINE_DEFINITION
  
	WHILE @@FETCH_STATUS = 0    
	BEGIN
		SET @vSFVT_Query += @vROUTINE_DEFINITION +CHAR(13)+'GO --'+CHAR(13)
        
		FETCH NEXT FROM create_table_script_cur INTO @vROUTINE_SCHEMA,@vROUTINE_NAME,@vROUTINE_TYPE,@vROUTINE_DEFINITION
   
	END     
CLOSE create_table_script_cur;
SELECT @vSFVT_Query
DEALLOCATE create_table_script_cur;    