CREATE OR ALTER PROCEDURE usp_GetDBObjectList
@vDB_NAME SYSNAME
AS
BEGIN
DECLARE @vObjectListTab	AS TABLE(ID INT IDENTITY,DB_Name SYSNAME,Object_Schema VARCHAR(100), Object_Name SYSNAME, Object_Type VARCHAR(100))

INSERT INTO @vObjectListTab
EXEC ('SELECT *	FROM ' + @vDB_NAME + '.INFORMATION_SCHEMA.TABLES T WHERE T.TABLE_TYPE = ''BASE TABLE''');

INSERT INTO @vObjectListTab
EXEC(
	'SELECT ''' + @vDB_NAME + ''' AS DB_Name, S.NAME COLLATE SQL_Latin1_General_CP1_CI_AS, 
	A.NAME COLLATE SQL_Latin1_General_CP1_CI_AS, 
	CASE WHEN A.TYPE=''P'' THEN ''PROCEDURE'' WHEN A.TYPE=''FN'' THEN ''FUNCTION'' WHEN A.TYPE=''V'' THEN ''VIEW'' WHEN A.TYPE=''TR'' THEN ''TRIGGER'' 
	ELSE A.TYPE_DESC END
	COLLATE SQL_Latin1_General_CP1_CI_AS 
	FROM ' + @vDB_NAME + '.SYS.OBJECTS A
	INNER JOIN ' + @vDB_NAME + '.SYS.SCHEMAS S On A.SCHEMA_ID = S.SCHEMA_ID
	WHERE A.TYPE IN(''P'',''V'',''FN'',''TR'')
	UNION
	SELECT ROUTINE_CATALOG,ROUTINE_SCHEMA,ROUTINE_NAME,ROUTINE_TYPE FROM ' + @vDB_NAME + '.INFORMATION_SCHEMA.ROUTINES'
	)

SELECT * FROM @vObjectListTab ORDER BY Object_Type
END