DECLARE @vTab1 AS TABLE(Name VARCHAR(500),XType CHAR(3),Cr_Date DateTime)
DECLARE @vTab AS TABLE (Obj_Type VARCHAR(50),Obj_Name VARCHAR(500),Table_Schema VARCHAR(100),Table_Name VARCHAR(500))
DECLARE @vObj_Type VARCHAR(50),@vObj_Schema VARCHAR(100),@vObj_Name VARCHAR(500)

DECLARE TableSearchInSP CURSOR
    FOR SELECT TABLE_SCHEMA,TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' --AND TABLE_NAME = 'GPM_Account'

	OPEN TableSearchInSP;
	FETCH NEXT FROM TableSearchInSP INTO @vObj_Schema,@vObj_Name
	WHILE @@FETCH_STATUS = 0
    BEGIN
		
		/*
		INSERT INTO @vTab1
		EXEC Sp_codesearch @vObj_Name

		INSERT INTO @vTab
		SELECT DISTINCT 
		CASE WHEN XTYPE='P' THEN 'PROCEDURE' WHEN XTYPE='FN' THEN 'FUNCTION' WHEN XTYPE='V' THEN 'VIEW' WHEN XTYPE='TR' THEN 'TRIGGER' ELSE XTYPE END,
		Name,@vObj_Schema,@vObj_Name FROM @vTab1

		DELETE FROM @vTab1
		*/
		
		/*
		INSERT INTO @vTab
		SELECT DISTINCT 
		CASE WHEN O.XTYPE='P' THEN 'PROCEDURE' WHEN O.XTYPE='FN' THEN 'FUNCTION' WHEN O.XTYPE='V' THEN 'VIEW' WHEN O.XTYPE='TR' THEN 'TRIGGER' ELSE O.XTYPE END,
		O.NAME,@vObj_Schema,@vObj_Name FROM SYSCOMMENTS C INNER JOIN SYSOBJECTS O ON C.ID=O.ID 
		WHERE C.TEXT LIKE '%'+@vObj_Name+'%'
		--AND O.XTYPE != 'TR'
		--CHARINDEX(@vObj_Name,C.TEXT)>0
		*/
		
		--/*
		--This Process Will Ignore Tables Used Inside Comment Section
		INSERT INTO @vTab
		SELECT CASE WHEN O.XTYPE='P' THEN 'PROCEDURE' WHEN O.XTYPE='FN' THEN 'FUNCTION' WHEN O.XTYPE='V' THEN 'VIEW' WHEN O.XTYPE='TR' THEN 'TRIGGER' ELSE O.XTYPE END AS Obj_Type,
		TAB.referencing_schema_name+'.'+TAB.referencing_entity_name AS Obj_Name,
		@vObj_Schema AS TABLE_SCHEMA, @vObj_Name AS TABLE_NAME FROM
		(
		SELECT REFERENCING_SCHEMA_NAME,REFERENCING_ENTITY_NAME
		FROM SYS.DM_SQL_REFERENCING_ENTITIES (@vObj_Schema+'.'+@vObj_Name, 'OBJECT') 
		) TAB
		INNER JOIN SYSOBJECTS O ON O.name = TAB.referencing_entity_name
		INNER JOIN SYS.SCHEMAS S ON S.name = TAB.referencing_schema_name
		--*/

        FETCH NEXT FROM TableSearchInSP INTO @vObj_Schema,@vObj_Name
    END;
	CLOSE TableSearchInSP;
	DEALLOCATE TableSearchInSP;

	SELECT DISTINCT * FROM @vTab ORDER BY Obj_Name
